# Generated by Django 3.1.1 on 2020-10-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitems',
            old_name='user_id',
            new_name='username',
        ),
    ]
