# Generated by Django 3.1.1 on 2020-10-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201018_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitems',
            old_name='username',
            new_name='user',
        ),
    ]
