# Generated by Django 3.1.4 on 2020-12-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_last_min', models.IntegerField(default=0)),
                ('requests_last_day', models.IntegerField(default=0)),
                ('hour_count', models.TimeField(auto_now_add=True)),
                ('min_count', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
